Appc 1051 develop billing standalone sdk
Aptoide/bds-sdk pull request #19
Opened 2019-04-18 12:02 UTC by brunovarelaAptoide

- New WS to get skuDetails
- New JSON mapper
- Removed Dependencies from android-appcoins-billing

2019-04-22 08:44 UTC, nunomonteiro requested changes
@brunovarelaAptoide 
Parece muito mas é mais texto e explicaçoes para o que tou a dizer de forma a perceberes o porque das coisas e ser mais fácil evitares o erro da próxima vez.
@JoaoRaimundo @Trinkes 
Primeira tentativa de eu agir como intermediário entre os pulls requests da equipa e vcs.
Sugiro que em vez de verem as changes, vejam só o feedback que eu dei e o validem. 
Se tiver tudo ok, mantemos este esquema e as cenas seguem para vcs após terem levado uma vista d'olhos minha. Boa?

2019-04-22 08:44 UTC, nunomonteiro commented on android-appcoins-billing/build.gradle
> +      buildConfigField 'String', 'BDS_WALLET_PACKAGE_NAME',
Shouldn't the dev package build with the dev wallet name?

2019-04-22 08:44 UTC, nunomonteiro commented on android-appcoins-billing/src/main/java/com/appcoins/sdk/android_appcoins_billing/CatapultAppcoinsBilling.java
> +public class CatapultAppcoinsBilling implements AppcoinsBillingClient , DialogVisibleListener {
I'm gonna be picky but these names matter to give the user a sense of the class purpose.
I know what you're trying to say but it's ambiguous. Does it listen to the dialog only when it's visible? I went ahead and saw that the answer is no. But the name should tell me this already.
I suggest changing it to IsDialogVisibleListerner or even better DialogVisibilityListener (you'll see why on the next comment)

2019-04-22 08:44 UTC, nunomonteiro commented on android-appcoins-billing/src/main/java/com/appcoins/sdk/android_appcoins_billing/CatapultAppcoinsBilling.java
> +  @Override public void OnDialogVisibleListener(boolean value) {
this function should be called onDialogVisibilityChanged. This way you know it's supposed to be called every time the visibility changes and not just when the dialog is visible. Also notice the lowercase o! Java methods should always start with lowercase letter.

2019-04-22 08:44 UTC, nunomonteiro commented on android-appcoins-billing/src/main/java/com/appcoins/sdk/android_appcoins_billing/helpers/AndroidBillingMapper.java
> +
Avoid empty catch statements at all costs! At least always log the exception with an error. If it's not your code, check with the last person to have committed there what an exception there might mean and treat it accordingly.

2019-04-22 08:44 UTC, nunomonteiro commented on android-appcoins-billing/src/main/java/com/appcoins/sdk/android_appcoins_billing/helpers/AndroidBillingMapper.java
> +
Same here

2019-04-22 08:44 UTC, nunomonteiro commented on android-appcoins-billing/src/main/java/com/appcoins/sdk/android_appcoins_billing/helpers/AndroidBillingMapper.java
> +
same here

2019-04-22 08:44 UTC, nunomonteiro commented on android-appcoins-billing/src/main/java/com/appcoins/sdk/android_appcoins_billing/helpers/AndroidBillingMapper.java
> +        e.printStackTrace();
This would be a good start

2019-04-22 08:44 UTC, nunomonteiro commented on android-appcoins-billing/src/main/java/com/appcoins/sdk/android_appcoins_billing/helpers/DialogVisibleListener.java
> +public interface DialogVisibleListener {
Same changes here:
filename
interface name
method name

2019-04-22 08:44 UTC, nunomonteiro commented on android-appcoins-billing/src/main/java/com/appcoins/sdk/android_appcoins_billing/helpers/PayloadHelper.java
> +  public static String buildIntentPayload(final String orderReference,
Will this always get arguments different from null now? This might require updates to documentation

2019-04-22 08:44 UTC, nunomonteiro commented on appcoins-billing/src/main/java/com/appcoins/sdk/billing/GetSkuDetailsService.java
> +    String url = serviceUrl + "/inapp/8.20180518/packages/packageName/products?names=".replaceFirst(
the hardcoded path should be a final at the top of the file for better maintainability of the code. If someone else would need to change the path they wouldn't have to fish that var in the middle of the file.

2019-04-22 08:44 UTC, nunomonteiro commented on toolbox/src/main/java/com/asf/appcoins/toolbox/Application.java
> +    //private static AppCoinsAds adsSdk;
Check with the Wallet team how to deal with the POA being present on the toolbox

2019-05-08 14:59 UTC, Trinkes requested changes

2019-05-08 14:59 UTC, Trinkes commented on android-appcoins-billing/src/main/java/com/appcoins/sdk/billing/helpers/AppcoinsBillingStubHelper.java
> +public class AppcoinsBillingStubHelper extends android.os.Binder implements AppcoinsBilling {
Why is this class extending Binder?

2019-05-08 14:59 UTC, Trinkes commented on android-appcoins-billing/src/main/java/com/appcoins/sdk/billing/helpers/AppcoinsBillingStubHelper.java
> +    return ResponseCode.OK.getValue();
since we are not consuming the purchase, we should answer with an error instead of the ok

2019-05-08 14:59 UTC, Trinkes commented on android-appcoins-billing/src/main/java/com/appcoins/sdk/billing/helpers/AppcoinsBillingStubHelper.java
> +    public static AppcoinsBilling AsInterface(IBinder service) {
the method name shouldn't start with a capital letter

2019-05-08 14:59 UTC, Trinkes commented on android-appcoins-billing/src/main/java/com/appcoins/sdk/billing/helpers/AppCoinsAndroidBillingRepository.java
> +  private final Context context;
Context is not used

2019-05-08 14:59 UTC, Trinkes commented on android-appcoins-billing/src/main/java/com/appcoins/sdk/billing/helpers/AppCoinsAndroidBillingRepository.java
> +import android.app.Activity;
not used

2019-05-08 14:59 UTC, Trinkes commented on android-appcoins-billing/src/main/java/com/appcoins/sdk/billing/helpers/AppCoinsAndroidBillingRepository.java
> +    this.context = context;
remove not used context

2019-05-08 14:59 UTC, Trinkes commented on android-appcoins-billing/src/main/java/com/appcoins/sdk/billing/helpers/PayloadHelper.java
> +package com.appcoins.sdk.billing.helpers;
why did you change PayloadHelper?

2019-05-08 14:59 UTC, Trinkes commented on android-appcoins-billing/src/main/java/com/appcoins/sdk/billing/helpers/WalletUtils.java
> +  public static Activity act;
no need for holding a static reference for the activity anymore

2019-05-08 14:59 UTC, Trinkes commented on scripts/publish.sh
> +export BUILD_NAME_SUFFIX=".dev"
do we want do commit this?

2019-05-21 17:58 UTC, Trinkes requested changes

2019-05-21 17:58 UTC, Trinkes commented on appcoins-billing/src/main/java/com/appcoins/sdk/billing/WSServiceController.java
> +  public static void setWsUrl(String url) {
remove this setter and use the build config value directly here

2019-05-22 14:20 UTC, Trinkes approved these changes

2019-05-22 14:25 UTC, merged