[APPC-1673] Added User Agent to requests
Aptoide/bds-sdk pull request #98
Opened 2020-03-09 12:08 UTC by JDSM01

**What does this PR do?**

   Adds user agent to sdk requests

**Database changed?**

 No

**Where should the reviewer start?**

BdsService.java
WalletUtils.java

**How should this be manually tested?**

Check with charles if the user agent is being sent on the requests

**What are the relevant tickets?**

https://aptoide.atlassian.net/browse/APPC-1673

**Code Review Checklist**

- [ ] Architecture
- [ ] Documentation on public interfaces
- [ ] Database changed?
- [ ] If yes - Database migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] Functional QA tests pass

2020-03-23 12:15 UTC, brunovarelaAptoide requested changes

2020-03-23 12:15 UTC, brunovarelaAptoide commented on android-appcoins-billing/src/main/java/com/appcoins/sdk/billing/helpers/WalletUtils.java
> +    if (userAgent == null) {
just to be more code clear maybe split these in 2.

2020-03-23 18:32 UTC, Trinkes requested changes
i know it wasn't added in this PR, but can you remove the unused field on CampaignService?

2020-03-23 18:32 UTC, Trinkes commented on appcoins-ads/src/main/java/com/asf/appcoins/sdk/ads/network/clients/CampaignService.java
>    protected String concat;
not used

2020-03-24 13:42 UTC, brunovarelaAptoide approved these changes

2020-03-24 15:40 UTC, merged